### PR TITLE
Switch to C binary

### PR DESCRIPTION
**Pull request by bryanyee33**
Now KSU can run 4 FPS as well! (Can probably run at much higher frame rates than this)

`combiner.py` is used to combine the multiple txt files into one.
`badapple` binary usage: ./badapple \<path\> \<height\> \<width\> \<frames\> \<sleep\> (flexibility for higher frame rate)
Compilation: `clang -O3 -o badapple badapple.c`

### CODE REVIEW

**Comment by backslashxx** [comment]
is it io bottlenecked?
will somethin like this solve it?
[action.zip](https://github.com/user-attachments/files/18218117/action.zip)

**Comment by bryanyee33** [comment]
Yes, it is most likely io bounded since all it is doing is reading & printing lines.
I assumed that was what you meant by KSU being unable to handle 0.5 sleep / 2fps.

On my device, your original version works similarly to my binary version (no lag at the start for both).
However, both seems to slow down & hang after a while, most likely due to a buffer limit in KSU manager (maybe this was the issue you were talking about?)

Even using multiple different methods, I was unable to clear the screen to fix this issue (I am thinking this isn't even a terminal, and is just an output screen), and am not sure how to fix this.

The `action.zip` method you gave is also a nice way to help with the io, but that base64 conversion is actually not necessary (it actually makes the output bigger since UTF-8 has 256 chars vs base64's 64 chars)
I made one without the encoding:
[action.sh.zip](https://github.com/user-attachments/files/18218466/action.sh.zip)

**Comment by backslashxx** [comment]
so it is bottlenecked by small file opens?
how about
[bad_apple.zip](https://github.com/user-attachments/files/18218467/bad_apple.zip)


I kinda deter away from binaries as I dont really have the aptitude to do them

--
yeah there seems to be a buffer issue, of you keep it below 300~ ? frames in total it seems to be fine
its not a real terminal, its just stdout, theres no sign of any real tty-ness on it

-- 
the base64 is to ease up the output on the converter script
https://github.com/backslashxx/bad-apple-ascii/commit/b2509564982ad701d3b3398bf85f7c4ace0494d1

**Comment by backslashxx** [comment]
> However, both seems to slow down & hang after a while, most likely due to a buffer limit in KSU manager (maybe this was the issue you were talking about?)

this needs to be reported maybe, but then I can't just say "bad apple modul crash in ksu"
since we are just abusing action for the sake of memes

**Comment by bryanyee33** [comment]
Using
`./ascii-image-converter -d 30,16 out0200.jpg | sed ':a;N;$!ba;s/\n/\\n/g' >> frames-ascii/frames.txt`
works to make the output have \n if you want to use it without base64.

Source: https://stackoverflow.com/questions/1251999/how-can-i-replace-each-newline-n-with-a-space-using-sed

**Comment by bryanyee33** [comment]
> this needs to be reported maybe, but then I can't just say "bad apple modul crash in ksu" since we are just abusing action for the sake of memes

Yea I'm trying to find out where this output is in the source code but I can't seem to find it.

**Comment by bryanyee33** [comment]
> this needs to be reported maybe, but then I can't just say "bad apple modul crash in ksu" since we are just abusing action for the sake of memes

I think this is the line appending the outputs: https://github.com/tiann/KernelSU/blob/83d7db0fbec3347f345e3c9b704e65dadf22db4a/manager/app/src/main/java/me/weishu/kernelsu/ui/screen/Flash.kt#L110
I don't think its possible to bypass this..

I doubt they will bother "fixing" this either since normal modules won't have this much output-

**Comment by backslashxx** [comment]
I tried doing pure utf8 right now
zip file is larger, check current master

https://github.com/backslashxx/bad-apple-ascii/commit/06a803f29bff5fa96a48f7f64a6bfd4ca0be0ac9
https://github.com/backslashxx/bad-apple-ascii/commit/c1be96cb42f937ea5153caa722eead92c420332e

**Comment by bryanyee33** [comment]
I think you accidentally included the actual jpg and previous frames.txt which made the zip file bigger.

Nice use of `sed -z`! Didn't know you could do that.

**Pull request closed without merging**
